name: Build firmware
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: ghcr.io/james-martinez/arduino-cli-esp8266:79cd3f43
    steps:
      - uses: actions/checkout@v1
        with:
          branch: main
      - name : Build 
        run: |
          cat test/test.ino
          arduino-cli compile -b esp8266:esp8266:generic test/test.ino
