name: Github Docker Image CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - run: | 
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-8)
        docker build -t ghcr.io/$GITHUB_REPOSITORY:$SHORT_SHA -t ghcr.io/$GITHUB_REPOSITORY:latest .
        docker push ghcr.io/$GITHUB_REPOSITORY:$SHORT_SHA
